"use client"

import { useState, useEffect } from "react"
import { AdminHeader } from "@/components/admin-header"
import { AnalyticsDashboard } from "@/components/admin/analytics/analytics-dashboard"
import { RevenueChart } from "@/components/admin/analytics/revenue-chart"
import { BookingStatusChart } from "@/components/admin/analytics/booking-status-chart"
import { CarUtilizationChart } from "@/components/admin/analytics/car-utilization-chart"
import { RevenueByCarTable } from "@/components/admin/analytics/revenue-by-car-table"
import { BookingTrendsTable } from "@/components/admin/analytics/booking-trends-table"
import { DateRangePicker } from "@/components/admin/analytics/date-range-picker"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { bookingsData, carsData } from "@/lib/data"
import { calculateAnalyticsData } from "@/lib/analytics"
import type { DateRange } from "@/lib/types"
import { subMonths } from "date-fns"

export function AnalyticsContent() {
  // Default date range: last 6 months to current date
  const [dateRange, setDateRange] = useState<DateRange>({
    from: subMonths(new Date(), 6),
    to: new Date(),
  })

  const [analyticsData, setAnalyticsData] = useState(() => calculateAnalyticsData(bookingsData, carsData, dateRange))

  // Update analytics data when date range changes
  useEffect(() => {
    setAnalyticsData(calculateAnalyticsData(bookingsData, carsData, dateRange))
  }, [dateRange])

  return (
    <div className="flex min-h-screen flex-col">
      <AdminHeader />
      <div className="container mx-auto p-4 py-8">
        <div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-center">
          <div>
            <h1 className="text-3xl font-bold">Analytics & Reporting</h1>
            <p className="text-muted-foreground">Track your business performance and booking trends</p>
          </div>
          <DateRangePicker dateRange={dateRange} onDateRangeChange={setDateRange} />
        </div>

        <AnalyticsDashboard data={analyticsData} />

        <div className="mt-8 grid gap-8 md:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Revenue Trends</CardTitle>
              <CardDescription>Monthly revenue over the selected period</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-80">
                <RevenueChart data={analyticsData.revenueByMonth} />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Booking Distribution</CardTitle>
              <CardDescription>Breakdown of bookings by status</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-80">
                <BookingStatusChart data={analyticsData.bookingsByStatus} />
              </div>
            </CardContent>
          </Card>
        </div>

        <Card className="mt-8">
          <CardHeader>
            <CardTitle>Car Utilization</CardTitle>
            <CardDescription>Percentage of time each car was rented during the selected period</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="h-80">
              <CarUtilizationChart data={analyticsData.carUtilization} />
            </div>
          </CardContent>
        </Card>

        <Tabs defaultValue="revenue" className="mt-8">
          <TabsList>
            <TabsTrigger value="revenue">Revenue by Car</TabsTrigger>
            <TabsTrigger value="bookings">Booking Trends</TabsTrigger>
          </TabsList>
          <TabsContent value="revenue" className="mt-4">
            <Card>
              <CardHeader>
                <CardTitle>Revenue by Car Model</CardTitle>
                <CardDescription>Total revenue generated by each car model</CardDescription>
              </CardHeader>
              <CardContent>
                <RevenueByCarTable data={analyticsData.revenueByCar} />
              </CardContent>
            </Card>
          </TabsContent>
          <TabsContent value="bookings" className="mt-4">
            <Card>
              <CardHeader>
                <CardTitle>Booking Trends</CardTitle>
                <CardDescription>Monthly booking statistics</CardDescription>
              </CardHeader>
              <CardContent>
                <BookingTrendsTable data={analyticsData.bookingTrends} />
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}
